Debug/SMRP_STEM: main.c util.c ProtoMon/ProtoMon.c SMRP/SMRP.c STEM/STEM.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/SMRP_STEM main.c util.c ProtoMon/ProtoMon.c SMRP/SMRP.c STEM/STEM.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
