Debug/DijkstrasAloha: main.c util.c Dijkstra/Dijkstra.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c
	gcc -g -o Debug/DijkstrasAloha main.c util.c Dijkstra/Dijkstra.c  ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c -lpthread -lm
