Debug/SMRPAloha: main.c util.c ProtoMon/ProtoMon.c SMRP/SMRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/SMRPAloha main.c util.c ProtoMon/ProtoMon.c SMRP/SMRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
