Debug/RMRP_MACAW: main.c util.c RMRP/RMRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c
	gcc -g -o Debug/RMRP_MACAW main.c util.c RMRP/RMRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c -lpthread -lm
