Debug/RMRPAloha: main.c util.c ProtoMon/ProtoMon.c RMRP/RMRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/RMRPAloha main.c util.c ProtoMon/ProtoMon.c RMRP/RMRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
