Debug/STRP_ALOHA_v2: benchmark/benchmark.c util.c ProtoMon/metric.c ProtoMon/ProtoMonV2.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/STRP_ALOHA_v2 benchmark/benchmark.c util.c ProtoMon/metric.c ProtoMon/ProtoMonV2.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
