Debug/AlohaRoute: main.c util.c TopoMap/TopoMap.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/AlohaRoute main.c util.c TopoMap/TopoMap.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
