Debug/AlohaRoute: main.c util.c common.c Routing/routing.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -o Debug/AlohaRoute main.c util.c common.c Routing/routing.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
