Debug/DijkstrasMACAW: main.c util.c Dijkstra/Dijkstra.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c
	gcc -g -o Debug/DijkstrasMACAW main.c util.c Dijkstra/Dijkstra.c  MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c -lpthread -lm
