Debug/STRPAloha: main.c util.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/STRPAloha main.c util.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
