Debug/SMRP_MACAW: main.c util.c SMRP/SMRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c
	gcc -g -o Debug/SMRP_MACAW main.c util.c SMRP/SMRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c ProtoMon/ProtoMon.c -lpthread -lm
