### For benchmark
# Debug/STRP_MACAW: benchmark/benchmark.c util.c ProtoMon/ProtoMon.c STRP/STRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c
# 	gcc -g -o Debug/STRP_MACAW benchmark/benchmark.c util.c ProtoMon/ProtoMon.c STRP/STRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
Debug/STRP_MACAW: main.c util.c ProtoMon/ProtoMon.c STRP/STRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/STRP_MACAW main.c util.c ProtoMon/ProtoMon.c STRP/STRP.c MACAW/MACAW.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
