#### For benchmark
# Debug/STRP_ALOHA: benchmark/benchmark.c util.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
# 	gcc -g -o Debug/STRP_ALOHA benchmark/benchmark.c util.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
Debug/STRP_Aloha: main.c util.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/STRP_Aloha main.c util.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm