Debug/STRP_ALOHA: benchmark/benchmark.c util.c ProtoMon/metric.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c
	gcc -g -o Debug/STRP_ALOHA benchmark/benchmark.c util.c ProtoMon/metric.c ProtoMon/ProtoMon.c STRP/STRP.c ALOHA/ALOHA.c SX1262/SX1262.c GPIO/GPIO.c -lpthread -lm
